---

- name: Create app/src directory
  file:
      path={{ APP_PATH }}/src
      state=directory
      mode=750
      owner="{{ APP_DEPLOY_USER }}"
      group=www-data

- name: Git checkout from public repo
  git:
    repo={{ APP_GIT_URL }}
    dest={{ APP_PATH }}/src/
    force=yes
    version={{ APP_GIT_BRANCH }}
  become: true
  become_user: "{{ APP_DEPLOY_USER }}"
  tags: code
  when: APP_GIT_DEPLOY_KEY == ''

- name: Git checkout from private repo
  git:
    repo={{ APP_GIT_URL }}
    dest={{ APP_PATH }}/src/
    force=yes
    version={{ APP_GIT_BRANCH }}
    key_file={{ APP_GIT_DEPLOY_KEY }}
  become: true
  become_user: "{{ APP_DEPLOY_USER }}"
  tags: code
  when: APP_GIT_DEPLOY_KEY != ''
