---

- name: Create database
  postgresql_db: name={{ APP_DB_NAME }}
                 encoding='UTF-8'
  become: yes
  become_user: postgres


- name: Create PostGIS extension
  postgresql_ext: name=postgis db={{ APP_DB_NAME }}
  become: yes
  become_user: postgres
  when: APP_DB_POSTGIS == True

- name: "Create {{ APP_DB_USER }} user"
  postgresql_user:
      db={{ APP_DB_NAME }}
      name={{ APP_DB_USER }}
      password={{ APP_DB_PASSWORD }}
      encrypted=True
  become: yes
  become_user: postgres


- name: "Create {{ APP_DB_SCHEMA }} schema"
  postgresql_schema:
    database: "{{ APP_DB_NAME }}"
    name: "{{ APP_DB_SCHEMA }}"
    owner: "{{ APP_DB_USER }}"
  become: yes
  become_user: postgres
  when: APP_DB_SCHEMA != ''


- name: "ALL privileges on {{ APP_DB_NAME }} to {{ APP_DB_USER }}"
  postgresql_privs: >
    db={{ APP_DB_NAME }}
    privs=ALL
    type=database
    role={{ APP_DB_USER }}
  become: yes
  become_user: postgres
  when: APP_DB_SCHEMA == ''
