---

- name: Required for ansible database
  apt: name={{ item }} state=latest
  with_items:
    - python-psycopg2

- include: db.yml
  when: APP_DB_CREATE == True and APP_DJANGO == True

- include: app.yml
