---

- name: Create app/venv directory
  file:
      path={{ APP_PATH }}/venv
      state=directory
      mode=750
      owner="{{ APP_DEPLOY_USER }}"
      group=www-data

- name: Find python version
  command: which python{{ APP_PYTHON_VERSION | ternary(APP_PYTHON_VERSION, APP_PYTHON3 | ternary('3', '2.7')) }}
  register: python_version_found

- name: "Create virtualenv python {{ APP_PYTHON_VERSION | ternary(APP_PYTHON_VERSION, APP_PYTHON3 | ternary('3', '2.7')) }}"
  pip:
      virtualenv_command="{{ python_version_found.stdout }} -m venv"
      virtualenv={{ APP_PATH }}/venv
      name=pip
      version=20.2.2
  become: true
  become_user: "{{ APP_DEPLOY_USER }}"
  when: "APP_PYTHON_VERSION | ternary(APP_PYTHON_VERSION, APP_PYTHON3 | ternary('3', '2.7')) != '2.7'"

- name: "Create virtualenv python {{ APP_PYTHON_VERSION | ternary(APP_PYTHON_VERSION, APP_PYTHON3 | ternary('3', '2.7')) }}"
  pip:
      virtualenv_python=python{{ APP_PYTHON_VERSION | ternary(APP_PYTHON_VERSION, APP_PYTHON3 | ternary('3', '2.7')) }}
      virtualenv={{ APP_PATH }}/venv
      name=pip
      version=20.2.2
  become: true
  become_user: "{{ APP_DEPLOY_USER }}"
  when: "APP_PYTHON_VERSION | ternary(APP_PYTHON_VERSION, APP_PYTHON3 | ternary('3', '2.7')) == '2.7'"
