---

- name: Create app/venv directory
  file:
      path={{ APP_PATH }}/venv
      state=directory
      mode=750
      owner="{{ APP_DEPLOY_USER }}"
      group=www-data

- name: Create virtualenv python {{ APP_PYTHON3 | ternary('3', '2.7') }}
  pip:
      virtualenv_python=python{{ APP_PYTHON3 | ternary('3', '2.7') }}
      virtualenv={{ APP_PATH }}/venv
      name=pip
      state=latest
  become: true
  become_user: "{{ APP_DEPLOY_USER }}"

# alternative with with_first_found
# - include: "{{ item }}"
#   with_first_found:
#     - files:
#         - default-{{ APP_PYTHON3 | ternary('python3', 'python2') }}.yml
#       paths:
#         - virtualenv/
