---

- name: "copy configuration... vars.ini"
  template:
    src=conf/{{ item }}.j2 dest={{ APP_PATH }}/{{ item }}
    owner=www-data
    group=www-data
    mode=0600
  with_items:
    - vars.ini
  tags: config
